// Check every printed figure in README.md and RESULTS.md against the json.
//
// Both documents are generated by eval/report.py, and `report.py --check`
// already fails if either has been edited by hand. That check compares
// report.py's output to report.py's own earlier output, so it cannot see a
// mistake inside report.py: if fmt() printed a rate at the wrong precision, or
// the ablation sentence read the wrong end of the sweep, --check would keep
// passing forever and the reader would keep seeing the wrong digits.
//
// This reads the committed markdown, pulls the numbers back out of it, and
// compares them to eval/results/eval_latest.json without going through
// report.py at all. Cells are compared numerically against half of the last
// printed digit, so this is a check that the digits a reader sees are the
// digits the data supports, not a check on rounding conventions.
//
// Run: node verify/published.js [root]

const fs = require('fs');
const path = require('path');

const root = process.argv[2] || '.';
const read = (...p) => fs.readFileSync(path.join(root, ...p), 'utf8');
const evalJson = JSON.parse(read('eval', 'results', 'eval_latest.json'));
const readme = read('README.md');
const results = read('RESULTS.md');

const problems = [];
let checked = 0;
let worst = 0; // largest gap as a fraction of the cell's own rounding tolerance

// A rate printed to one decimal of a percentage carries 0.0005 of resolution;
// a score printed to three decimals carries 0.0005 as well.
function agree(where, printed, actual, halfUlp) {
  checked += 1;
  if (printed === null || Number.isNaN(printed)) {
    problems.push(`${where}: could not read a number out of the document`);
    return;
  }
  const d = Math.abs(printed - actual);
  const ratio = halfUlp > 0 ? d / halfUlp : (d > 0 ? Infinity : 0);
  if (ratio > worst) worst = ratio;
  // A value printed exactly on a rounding boundary lands one float wobble
  // past the half-ulp, which is agreement, not a discrepancy.
  if (d > halfUlp * (1 + 1e-9)) {
    problems.push(`${where}: printed ${printed}, data says ${actual}, |d| ${d.toExponential(2)}`);
  }
}

const asRate = (cell) => {
  const m = /(-?[\d.]+)\s*%/.exec(cell);
  return m ? parseFloat(m[1]) / 100 : null;
};
const asNum = (cell) => {
  const m = /(-?[\d.]+)/.exec(cell.replace(/[*`]/g, ''));
  return m ? parseFloat(m[1]) : null;
};

const rateUlp = 0.0005;   // one decimal of a percent
const scoreUlp = 0.0005;  // three decimals of a 0..1 score

// --- markdown tables -------------------------------------------------------

// Every run of consecutive lines beginning with a pipe is one table. The
// separator row is dropped; cells keep their bold markers, which the readers
// above strip.
function tables(text) {
  const out = [];
  let cur = null;
  for (const line of text.split('\n')) {
    if (line.trimStart().startsWith('|')) {
      const cells = line.trim().replace(/^\||\|$/g, '').split('|').map((c) => c.trim());
      if (/^:?-{2,}/.test(cells[0])) continue;
      if (!cur) { cur = { header: cells, rows: [] }; out.push(cur); } else cur.rows.push(cells);
    } else {
      cur = null;
    }
  }
  return out;
}

function tableWith(text, ...headerWords) {
  const found = tables(text).filter((t) => headerWords.every((w) => t.header.includes(w)));
  if (found.length !== 1) {
    problems.push(`expected exactly one table with columns ${headerWords.join('/')}, found ${found.length}`);
    return null;
  }
  return found[0];
}

// --- the README retrieval table -------------------------------------------

const START = '<!-- RETRIEVAL_TABLE:START -->';
const END = '<!-- RETRIEVAL_TABLE:END -->';
const k = String(evalJson.config.top_k);
const labels = { 'dense (bge-small)': 'dense', BM25: 'bm25', 'hybrid (RRF)': 'hybrid' };

if (!readme.includes(START) || !readme.includes(END)) {
  problems.push('README.md has lost its retrieval table markers');
} else {
  const block = readme.split(START)[1].split(END)[0];
  const t = tables(block)[0];
  const cols = ['hit rate', 'recall', 'full recall', 'MRR', 'nDCG', 's/query'];
  const keys = ['hit_rate', 'recall', 'full_recall', 'mrr', 'ndcg', null];
  if (!t || t.rows.length !== Object.keys(evalJson.retrieval).length) {
    problems.push(`README retrieval table has ${t ? t.rows.length : 0} rows, the json has ${Object.keys(evalJson.retrieval).length} strategies`);
  } else {
    for (const row of t.rows) {
      const label = row[0].replace(/\*/g, '').trim();
      const mode = labels[label];
      if (!mode || !evalJson.retrieval[mode]) {
        problems.push(`README retrieval table has a row labelled "${label}", which is not a strategy in the json`);
        continue;
      }
      const s = evalJson.retrieval[mode].at_k[k].overall;
      cols.forEach((c, i) => {
        const cell = row[1 + i];
        const where = `README table ${label} ${c}`;
        if (keys[i] === null) {
          agree(where, asNum(cell), evalJson.retrieval[mode].latency_s_per_query, 0.0005);
        } else if (i < 3) {
          agree(where, asRate(cell), s[keys[i]], rateUlp);
        } else {
          agree(where, asNum(cell), s[keys[i]], scoreUlp);
        }
      });
    }
  }
}

// --- README prose ----------------------------------------------------------

const hybrid = evalJson.retrieval.hybrid.at_k[k];
const abl = evalJson.ablation_recital_weight;
const belowTop = Object.keys(abl).sort((a, b) => b - a).slice(1);
const summary = evalJson.summary;

// Each entry pins one sentence to one value. The regex has to be specific
// enough that it cannot match a different number further down the page.
const prose = [
  ['hybrid hit rate', /([\d.]+)% of questions get at least one\s+correct provision/, hybrid.overall.hit_rate, rateUlp],
  ['multi-hop full recall', /only ([\d.]+)% of those get everything they need/, hybrid.by_type.multi_hop.full_recall, rateUlp],
  ['multi-hop hit rate', /finds something relevant\s+for ([\d.]+)% of them/, hybrid.by_type.multi_hop.hit_rate, rateUlp],
  ['multi-hop full recall, again', /and everything they need for ([\d.]+)%/, hybrid.by_type.multi_hop.full_recall, rateUlp],
  ['multi-hop full recall, limitations', /\*\*([\d.]+)% full recall on multi-hop questions/, hybrid.by_type.multi_hop.full_recall, rateUlp],
  ['ablation MRR before', /moved MRR from\s*\n?([\d.]+) to/, abl['1.0'].mrr, scoreUlp],
  ['ablation MRR after', /moved MRR from\s*\n?[\d.]+ to ([\d.]+)/, abl[String(evalJson.config.recital_weight)].mrr, scoreUlp],
  ['ablation nDCG floor', /nDCG only creeps from ([\d.]+)/, Math.min(...belowTop.map((w) => abl[w].ndcg)), scoreUlp],
  ['ablation nDCG ceiling', /nDCG only creeps from [\d.]+\s*\n?to ([\d.]+)/, Math.max(...belowTop.map((w) => abl[w].ndcg)), scoreUlp],
  ['faithfulness', /\*\*Faithfulness\*\*[^|]*\|\s*\*\*([\d.]+)%/, summary.faithfulness, rateUlp],
  ['citation validity', /\*\*Citation validity\*\*[^|]*\|\s*\*\*([\d.]+)%/, summary.citation_validity, rateUlp],
  ['correct abstention', /\*\*Correct abstention\*\*[^|]*\|\s*\*\*([\d.]+)%/, summary.correct_abstention_rate, rateUlp],
  ['hallucination rate', /\*\*Hallucination rate\*\*[^|]*\|\s*\*\*([\d.]+)%/, summary.hallucination_rate_unanswerable, rateUlp],
  ['accuracy strict', /Answer accuracy, strict \| ([\d.]+)%/, summary.answer_accuracy_strict, rateUlp],
  ['accuracy lenient', /Answer accuracy, incl\. partially correct \| ([\d.]+)%/, summary.answer_accuracy_lenient, rateUlp],
  ['false abstention', /False abstention \(refused a question it could answer\) \| ([\d.]+)%/, summary.false_abstention_rate, rateUlp],
  ['n questions', /([\d]+) hand-written questions over/, evalJson.config.n_questions, 0],
  ['n chunks', /\*\*([\d]+) chunks\*\*/, evalJson.config.n_chunks, 0],
];

for (const [name, re, actual, ulp] of prose) {
  const m = re.exec(readme);
  if (!m) { problems.push(`README: no sentence matching the ${name} claim`); checked += 1; continue; }
  const v = ulp === 0 ? parseFloat(m[1]) : parseFloat(m[1]) / (re.source.includes('%') ? 100 : 1);
  agree(`README ${name}`, v, actual, ulp === 0 ? 0 : ulp);
}

// The one arithmetic claim in the README that no json holds: the corpus is
// described as 113 articles + 180 recitals + 13 annexes making 464 chunks.
{
  const kinds = { article: new Set(), recital: new Set(), annex: new Set() };
  let nChunks = 0;
  for (const line of read('data', 'processed', 'chunks.jsonl').split('\n')) {
    if (!line.trim()) continue;
    const c = JSON.parse(line);
    nChunks += 1;
    if (kinds[c.kind]) kinds[c.kind].add(c.unit_id);
  }
  const m = /(\d+) articles \+ (\d+) recitals \+ (\d+) annexes[^\d]+\*\*(\d+) chunks\*\*/.exec(readme);
  if (!m) {
    problems.push('README: no sentence describing the corpus as articles + recitals + annexes');
  } else {
    agree('README articles', parseInt(m[1], 10), kinds.article.size, 0);
    agree('README recitals', parseInt(m[2], 10), kinds.recital.size, 0);
    agree('README annexes', parseInt(m[3], 10), kinds.annex.size, 0);
    agree('README chunk total', parseInt(m[4], 10), nChunks, 0);
  }
}

// --- RESULTS.md ------------------------------------------------------------

{
  const t = tableWith(results, 'strategy', 'precision', 's/query');
  if (t) {
    for (const row of t.rows) {
      const mode = row[0].replace(/\*/g, '');
      const s = evalJson.retrieval[mode] && evalJson.retrieval[mode].at_k[k].overall;
      if (!s) { problems.push(`RESULTS.md strategy table has an unknown row "${mode}"`); continue; }
      ['hit_rate', 'recall', 'full_recall', 'precision'].forEach((key, i) =>
        agree(`RESULTS all@k ${mode} ${key}`, asRate(row[1 + i]), s[key], rateUlp));
      agree(`RESULTS all@k ${mode} mrr`, asNum(row[5]), s.mrr, scoreUlp);
      agree(`RESULTS all@k ${mode} ndcg`, asNum(row[6]), s.ndcg, scoreUlp);
      agree(`RESULTS all@k ${mode} latency`, asNum(row[7]), evalJson.retrieval[mode].latency_s_per_query, 0.0005);
    }
  }
}

{
  const t = tableWith(results, 'strategy', 'type', 'full recall');
  if (t) {
    for (const row of t.rows) {
      const s = evalJson.retrieval[row[0]] && evalJson.retrieval[row[0]].at_k[k].by_type[row[1]];
      if (!s) { problems.push(`RESULTS.md by-type table has an unknown row "${row[0]}/${row[1]}"`); continue; }
      ['hit_rate', 'recall', 'full_recall'].forEach((key, i) =>
        agree(`RESULTS by_type ${row[0]}/${row[1]} ${key}`, asRate(row[2 + i]), s[key], rateUlp));
      agree(`RESULTS by_type ${row[0]}/${row[1]} mrr`, asNum(row[5]), s.mrr, scoreUlp);
    }
  }
}

{
  const t = tableWith(results, 'strategy', 'hit@3');
  if (t) {
    const ks = t.header.slice(1).filter((h) => h.startsWith('hit@')).map((h) => h.slice(4));
    for (const row of t.rows) {
      const md = evalJson.retrieval[row[0]];
      if (!md) { problems.push(`RESULTS.md sensitivity table has an unknown row "${row[0]}"`); continue; }
      ks.forEach((kk, i) => {
        agree(`RESULTS sensitivity ${row[0]} hit@${kk}`, asRate(row[1 + i]), md.at_k[kk].overall.hit_rate, rateUlp);
        agree(`RESULTS sensitivity ${row[0]} full@${kk}`, asRate(row[1 + ks.length + i]), md.at_k[kk].overall.full_recall, rateUlp);
      });
    }
  }
}

{
  const t = tableWith(results, 'w', 'nDCG');
  if (t) {
    for (const row of t.rows) {
      const w = row[0].replace(/\s*\(default\)\s*/, '');
      const s = abl[w];
      if (!s) { problems.push(`RESULTS.md ablation table has an unknown weight "${w}"`); continue; }
      ['hit_rate', 'recall', 'full_recall'].forEach((key, i) =>
        agree(`RESULTS ablation w=${w} ${key}`, asRate(row[1 + i]), s[key], rateUlp));
      agree(`RESULTS ablation w=${w} mrr`, asNum(row[4]), s.mrr, scoreUlp);
      agree(`RESULTS ablation w=${w} ndcg`, asNum(row[5]), s.ndcg, scoreUlp);
    }
  }
}

{
  const t = tableWith(results, 'metric', 'value', 'what it means');
  const byLabel = {
    'Answer accuracy (strict)': 'answer_accuracy_strict',
    'Answer accuracy (incl. partial)': 'answer_accuracy_lenient',
    Faithfulness: 'faithfulness',
    'Citation validity': 'citation_validity',
    'Correct abstention': 'correct_abstention_rate',
    'Hallucination rate (out-of-scope)': 'hallucination_rate_unanswerable',
    'False abstention': 'false_abstention_rate',
  };
  if (t) {
    for (const row of t.rows) {
      const label = row[0].replace(/\*/g, '').trim();
      if (label === 'Mean latency') {
        agree('RESULTS mean latency', asNum(row[1]), summary.mean_latency_s, 0.005);
      } else if (byLabel[label]) {
        agree(`RESULTS ${label}`, asRate(row[1]), summary[byLabel[label]], rateUlp);
      } else {
        problems.push(`RESULTS.md answer-quality table has an unknown row "${label}"`);
      }
    }
  }
}

{
  const t = tableWith(results, 'type', 'n', 'accuracy (strict)');
  if (t) {
    for (const row of t.rows) {
      const s = summary.by_type[row[0]];
      if (!s) { problems.push(`RESULTS.md by-question-type table has an unknown row "${row[0]}"`); continue; }
      agree(`RESULTS by type ${row[0]} n`, asNum(row[1]), s.n, 0);
      agree(`RESULTS by type ${row[0]} accuracy`, asRate(row[2]), s.accuracy_strict, rateUlp);
      if (s.faithfulness === null) {
        checked += 1;
        if (row[3] !== 'n/a') problems.push(`RESULTS by type ${row[0]} faithfulness: printed "${row[3]}", the json has null`);
      } else {
        agree(`RESULTS by type ${row[0]} faithfulness`, asRate(row[3]), s.faithfulness, rateUlp);
      }
    }
  }
}

{
  const t = tableWith(results, 'failure mode', 'n', 'meaning');
  if (t) {
    const seen = new Set();
    for (const row of t.rows) {
      const mode = row[0].replace(/`/g, '');
      seen.add(mode);
      if (!(mode in summary.failure_modes)) {
        problems.push(`RESULTS.md failure table has an unknown mode "${mode}"`);
        continue;
      }
      agree(`RESULTS failure ${mode}`, asNum(row[1]), summary.failure_modes[mode], 0);
    }
    for (const mode of Object.keys(summary.failure_modes)) {
      if (!seen.has(mode)) problems.push(`RESULTS.md failure table omits "${mode}"`);
    }
  }
}

if (problems.length) {
  for (const p of problems) console.error('  ' + p);
  console.error(`  ${problems.length} disagreement(s) out of ${checked} published figures`);
  process.exit(1);
}
console.log(`  ${checked} printed figures in README.md and RESULTS.md match the json`);
console.log(`  worst gap: ${worst.toFixed(3)} of the half-ulp of the cell's own last digit`);
console.log('  (1.000 is a value sitting exactly on a rounding boundary, which is agreement)');
